version: '2.3'
services:
  # this spins up a server that serves the html/js/css for the e2e tests
  e2e-server:
    command: yarn e2e:serve
    build:
      dockerfile: e2e.Dockerfile
      context: .
    expose:
      - 8080
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -H "Accept: text/html" -f http://e2e-server:8080 || exit 1',
        ]
      interval: 5s
      timeout: 10s
      retries: 5

  # tests if the e2e-server is ready to serve traffic
  e2e-server-healthy:
    build: .
    links:
      - e2e-server
    depends_on:
      e2e-server:
        condition: service_healthy

  # running the e2e tests in ci
  e2e-test:
    build: .
    links:
      - e2e-server
    volumes:
      - ./__artifacts__:/baseui/__artifacts__:delegated
      - ./vrt/__image_snapshots__:/baseui/vrt/__image_snapshots__:delegated
    depends_on:
      - e2e-server-healthy
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_PULL_REQUEST_REPO
      - GITHUB_BOT_AUTH_TOKEN
      - GITHUB_BOT_EMAIL
      - GITHUB_BOT_NAME

  baseui:
    build: .
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_PULL_REQUEST_REPO
      - BUILDKITE_COMMIT
      - BUILDKITE_MESSAGE
      - GITHUB_AUTH_TOKEN
      - ZEIT_NOW_TOKEN
      - FOSSA_API_KEY
      - CF_ZONE_ID
      - CF_ACCOUNT_ID
      - CF_API_KEY
      - CF_AUTH_EMAIL
      - NPM_TOKEN
      - NETLIFY_AUTH_TOKEN
      - NETLIFY_SITE_ID
      - AZURE_TOKEN
      - WEBSITE_ENV
